title: PAThs ERC
description: PAThs ERC Advanced project by Paola Buzi, hosted at Sapienza University of Rome offcial page
logo: paths-logo.png

collections:
  news:
    output: true
  team:
    output: true

exclude: [migration/]
